# Generated by Django 3.2.9 on 2021-11-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='problem',
            new_name='hotel',
        ),
    ]
